# Generated by Django 4.1.7 on 2023-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellidopaterno', models.CharField(max_length=25, verbose_name='Apellido paterno')),
                ('apellidomaterno', models.CharField(max_length=25, verbose_name='Apellido materno')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ncontrol', models.CharField(max_length=15, verbose_name='N.Control')),
                ('lugarnacimiento', models.CharField(max_length=25, verbose_name='Lugar nacimiento')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('estadocivil', models.CharField(max_length=30, verbose_name='Estado civil')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('domicilio', models.CharField(max_length=30, verbose_name='Domicilio')),
                ('colonia', models.CharField(max_length=18, verbose_name='Colonia')),
                ('codigopostal', models.CharField(max_length=5, verbose_name='Codigo postal')),
                ('ciudadolocalidad', models.CharField(max_length=25, verbose_name='Ciudad o localidad')),
                ('entidadfederativa', models.CharField(max_length=20, verbose_name='Entidad federativa')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('curp', models.CharField(max_length=18, verbose_name='Curp')),
                ('correoelectronico', models.CharField(blank=True, max_length=74, verbose_name='Correo electronico')),
                ('modalidad', models.CharField(max_length=1, verbose_name='Modalidad')),
                ('escuelasdeprocedencia', models.CharField(max_length=20, verbose_name='Escuela de procedencia')),
                ('direccion', models.CharField(max_length=70, verbose_name='Direccion')),
                ('carrera', models.CharField(blank=True, max_length=50, verbose_name='Carrera')),
                ('modcarrera', models.CharField(blank=True, max_length=15, verbose_name='Modalidad Carrera')),
                ('periododeingreso', models.CharField(blank=True, max_length=12, verbose_name='Periodo de ingreso')),
            ],
        ),
    ]
