# Generated by Django 4.2 on 2023-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecarrera', models.CharField(max_length=50, verbose_name='Nombre carrera')),
                ('clavecarrera', models.CharField(max_length=18, verbose_name='Clave')),
            ],
        ),
        migrations.CreateModel(
            name='Entidadfederativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entfederativa', models.CharField(max_length=20, verbose_name='Entidad Federativa')),
            ],
        ),
        migrations.CreateModel(
            name='Escuelaprocedencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=1, verbose_name='Modalidad')),
                ('escueladeprocedencia', models.CharField(max_length=40, verbose_name='Escuela de Procedencia')),
                ('direccion', models.CharField(max_length=80, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Estadocivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estcivil', models.CharField(max_length=30, verbose_name='Estado civil')),
            ],
        ),
        migrations.CreateModel(
            name='Materiasacursar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materia1', models.CharField(max_length=45, verbose_name='Materia1')),
                ('materia2', models.CharField(max_length=45, verbose_name='Materia2')),
                ('materia3', models.CharField(max_length=45, verbose_name='Materia3')),
                ('materia4', models.CharField(max_length=45, verbose_name='Materia4')),
                ('materia5', models.CharField(max_length=45, verbose_name='Materia5')),
                ('materia6', models.CharField(max_length=45, verbose_name='Materia6')),
            ],
        ),
        migrations.CreateModel(
            name='Modcarrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modacarrera', models.CharField(max_length=15, verbose_name='Modalidad de carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Periodoingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=12, verbose_name='Periodo Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='PlanesdeEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(blank=True, max_length=4, verbose_name='Semestre')),
                ('carrera', models.CharField(blank=True, max_length=45, verbose_name='Carrera')),
                ('especialidad', models.CharField(blank=True, max_length=55, verbose_name='Especialidad')),
                ('reticula', models.CharField(blank=True, max_length=13, verbose_name='Reticula')),
                ('clave', models.CharField(blank=True, max_length=16, verbose_name='Clave')),
                ('asignatura', models.CharField(blank=True, max_length=55, verbose_name='Asignatura')),
                ('clave1', models.CharField(blank=True, max_length=4, verbose_name='Clave1')),
                ('clave2', models.CharField(blank=True, max_length=8, verbose_name='Clave2')),
                ('hrsteoria', models.SmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Hrsteoria')),
                ('hrspractica', models.SmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Hrspractica')),
                ('creditos', models.SmallIntegerField(blank=True, verbose_name='creditos')),
                ('nmateria', models.SmallIntegerField(blank=True, max_length=2, null=True, verbose_name='nmateria')),
                ('prerequisito', models.IntegerField(blank=True, max_length=8, null=True, verbose_name='prerequisito')),
                ('tipomateria', models.CharField(blank=True, max_length=7, verbose_name='Tipo materia')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=10, verbose_name='Sexo')),
            ],
        ),
    ]
